# Generated by Django 2.2.4 on 2019-08-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='discription',
            new_name='description',
        ),
    ]
